ALTER TABLE informes
  ADD COLUMN IF NOT EXISTS odoo_estado VARCHAR(40) NOT NULL DEFAULT 'pendiente',
  ADD COLUMN IF NOT EXISTS odoo_ticket_ref VARCHAR(120) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS odoo_ticket_id BIGINT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS odoo_attachment_id BIGINT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS odoo_nombre_adjunto VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS odoo_error TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS odoo_intentos INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS odoo_ultimo_intento_en DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS odoo_sincronizado_en DATETIME DEFAULT NULL;
