<style>
:root{--bg:#eef2f7;--ink:#10213a;--muted:#66748a;--accent:#1f6fc4;--accent2:#23a6d5;--line:#dbe5f0;--card:#ffffff;--danger:#dc2626;--ok:#16a34a;}
*{box-sizing:border-box;margin:0;padding:0}
html,body{min-height:100%;font-family:Manrope,system-ui,-apple-system,Segoe UI,sans-serif;background:var(--bg);color:var(--ink)}
.zg-screen{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:28px;position:relative;overflow:hidden;background:linear-gradient(180deg,rgba(7,18,34,.58),rgba(7,18,34,.72)),url('zgroup-tec.jpg') center/cover no-repeat;}
.zg-screen:after{content:'';position:absolute;inset:auto 0 0;height:180px;background:linear-gradient(0deg,var(--bg),transparent);pointer-events:none}
.zg-card{position:relative;z-index:2;width:min(980px,100%);background:rgba(255,255,255,.94);border:1px solid rgba(255,255,255,.72);border-radius:28px;box-shadow:0 28px 70px rgba(0,0,0,.28);overflow:hidden;backdrop-filter:blur(12px)}
.zg-top{padding:28px 30px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:18px;justify-content:space-between;background:linear-gradient(180deg,#fff,#f7fbff)}
.zg-brand{display:flex;align-items:center;gap:16px}.zg-brand img{height:54px;width:auto;background:#fff;border-radius:16px;padding:8px;box-shadow:0 8px 22px rgba(16,33,58,.12)}
.zg-kicker{display:inline-flex;align-items:center;gap:7px;background:#e8f2ff;color:#13579b;border:1px solid #cbe1fa;border-radius:999px;padding:6px 11px;font-weight:900;letter-spacing:.12em;text-transform:uppercase;font-size:11px}.zg-kicker:before{content:'●';color:#f5b21b}
.zg-title{font-family:Archivo,system-ui,sans-serif;font-size:clamp(28px,4vw,44px);line-height:1;margin:10px 0 6px;letter-spacing:-.04em}.zg-sub{color:var(--muted);font-weight:700;font-size:14px;line-height:1.45}
.zg-body{padding:30px}.zg-actions{display:grid;grid-template-columns:1fr 1fr;gap:18px}.zg-option{display:flex;min-height:190px;flex-direction:column;justify-content:space-between;text-decoration:none;color:inherit;border:1.5px solid var(--line);border-radius:24px;background:linear-gradient(180deg,#fff,#f8fbff);padding:24px;transition:.18s;box-shadow:0 12px 34px rgba(16,33,58,.08)}
.zg-option:hover{transform:translateY(-3px);border-color:#9fc8f3;box-shadow:0 20px 45px rgba(31,111,196,.18)}.zg-option.disabled:hover{transform:none;border-color:var(--line)}
.zg-icon{width:52px;height:52px;border-radius:18px;display:grid;place-items:center;background:#e8f2ff;font-size:25px;margin-bottom:16px}.zg-option h2{font-family:Archivo,system-ui,sans-serif;font-size:24px;letter-spacing:-.02em;margin-bottom:7px}.zg-option p{color:var(--muted);font-weight:700;font-size:14px}.zg-go{margin-top:22px;display:inline-flex;align-items:center;justify-content:center;width:max-content;background:var(--accent);color:#fff;border-radius:999px;padding:11px 16px;font-weight:900;font-size:13px}.zg-muted-btn{background:#e9eef5;color:#10213a}.zg-logout{color:#567;align-self:flex-start;text-decoration:none;font-weight:900;background:#eef4fb;border:1px solid #d7e5f5;border-radius:999px;padding:9px 13px;font-size:12px}.zg-form{max-width:480px;margin:0 auto}.zg-input{width:100%;border:1.5px solid var(--line);border-radius:16px;padding:15px 16px;font:inherit;font-size:16px;background:#f8fbff;outline:none}.zg-input:focus{border-color:var(--accent);box-shadow:0 0 0 4px #e5f1ff}.zg-btn{width:100%;border:none;background:var(--accent);color:#fff;border-radius:16px;padding:15px 16px;font:inherit;font-weight:900;font-size:16px;cursor:pointer;margin-top:14px}.zg-error{margin-top:12px;background:#fff1f1;color:#b91c1c;border:1px solid #fecaca;border-radius:14px;padding:12px 14px;font-weight:800;font-size:13px}.zg-note{margin-top:14px;color:var(--muted);font-weight:700;font-size:13px;text-align:center}.zg-process{display:grid;grid-template-columns:1.1fr .9fr;gap:24px;align-items:center}.zg-anim{height:260px;border-radius:24px;background:radial-gradient(circle at 30% 25%,#dff1ff,transparent 34%),linear-gradient(145deg,#f8fbff,#eaf3ff);border:1px solid var(--line);display:grid;place-items:center;overflow:hidden}.zg-gear{font-size:84px;animation:zgSpin 3.5s linear infinite;filter:drop-shadow(0 14px 18px rgba(16,33,58,.2))}@keyframes zgSpin{to{transform:rotate(360deg)}}.zg-back{display:inline-flex;margin-top:18px;text-decoration:none;background:var(--accent);color:white;border-radius:999px;padding:12px 17px;font-weight:900}.zg-progress{height:12px;background:#e0e8f2;border-radius:999px;overflow:hidden;margin-top:18px}.zg-progress span{display:block;height:100%;width:48%;background:linear-gradient(90deg,var(--accent),var(--accent2));border-radius:999px;animation:zgLoad 1.8s ease-in-out infinite}@keyframes zgLoad{0%,100%{transform:translateX(-30%)}50%{transform:translateX(130%)}}
@media(max-width:720px){.zg-screen{padding:14px;align-items:flex-start}.zg-card{border-radius:22px;margin-top:18px}.zg-top{flex-direction:column;align-items:flex-start;padding:22px}.zg-body{padding:22px}.zg-actions{grid-template-columns:1fr}.zg-option{min-height:160px}.zg-process{grid-template-columns:1fr}.zg-anim{height:190px}.zg-logout{align-self:flex-end}}
.menu-home-float{position:fixed;top:18px;left:18px;z-index:120;display:inline-flex;align-items:center;gap:8px;border:1px solid rgba(255,255,255,.28);background:rgba(16,33,58,.82);color:#fff;border-radius:999px;padding:10px 14px;font-family:'Archivo',system-ui,sans-serif;font-size:13px;font-weight:900;cursor:pointer;box-shadow:0 14px 32px rgba(10,21,38,.22);backdrop-filter:blur(12px)}
.menu-home-float:hover{background:rgba(31,111,196,.92);transform:translateY(-1px)}
.leave-modal{position:fixed;inset:0;z-index:250;display:none;align-items:center;justify-content:center;background:rgba(10,21,38,.58);padding:18px;backdrop-filter:blur(7px)}
.leave-modal.show{display:flex}
.leave-box{width:min(520px,100%);background:#fff;border-radius:24px;border:1px solid #dbe6f3;box-shadow:0 24px 70px rgba(10,21,38,.32);overflow:hidden}
.leave-head{display:flex;align-items:center;gap:12px;padding:18px 20px;background:linear-gradient(135deg,#f8fbff,#eef5ff);border-bottom:1px solid #dbe6f3}
.leave-ico{width:42px;height:42px;border-radius:14px;display:grid;place-items:center;background:#fff3cd;color:#8a5a00;font-size:22px;border:1px solid #ffe29a}
.leave-head h3{font-family:'Archivo',system-ui,sans-serif;margin:0;color:#10213a;font-size:19px;letter-spacing:-.02em}
.leave-body{padding:18px 20px;color:#5d6d83;font-weight:700;line-height:1.45}
.leave-actions{display:flex;justify-content:flex-end;gap:10px;padding:0 20px 20px;flex-wrap:wrap}
.leave-btn{border:none;border-radius:14px;padding:12px 15px;font-family:'Archivo',system-ui,sans-serif;font-weight:900;cursor:pointer}
.leave-keep{background:#eaf1f8;color:#10213a}
.leave-exit{background:#1f6fc4;color:#fff;box-shadow:0 10px 22px rgba(31,111,196,.22)}
.leave-keep:hover,.leave-exit:hover{filter:brightness(.97);transform:translateY(-1px)}
@media(max-width:640px){.menu-home-float{top:10px;left:10px;padding:9px 11px;font-size:12px}.leave-actions{flex-direction:column-reverse}.leave-btn{width:100%}}
</style>
